# Generated by Django 5.0 on 2023-12-07 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2023, 12, 7, 15, 46, 29, 140809))),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
