# Generated by Django 5.0 on 2023-12-11 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_finished_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 12, 4, 16, 799896)),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.IntegerField(),
        ),
    ]
